name: deploy

on:
  push:
    branches:
      - main

jobs:
  unit-testing-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add your unit testing steps here

  deploy:
    needs: unit-testing-production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #  https://github.com/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install AWS CLI
        run: python3 -m pip install --user awscli

      - name: Deploy to AWS
        run: sh ./.configs/scripts/deploy-production.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_SHA: ${{ github.sha }}