name: codeblox-build-tests

on:
  pull_request:
    branches:
      - main

jobs: 
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env.test file
        run: |
          echo "POSTGRES_HOST_ALIAS=${{ secrets.POSTGRES_HOST_ALIAS }}" >> .configs/.env.test
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .configs/.env.test
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .configs/.env.test
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .configs/.env.test
          echo "ORGANIZATION=${{ secrets.ORGANIZATION }}" >> .configs/.env.test

      - name: Run tests with Docker Compose
        run: NODE_ENV=test docker compose -f .docker/docker-compose-test.yml -f .docker/docker-compose-postgres.test.yml up --abort-on-container-exit
